dvc update

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -23,6 +23,26 @@ jobs:
           python -m pip install --upgrade pip
           pip install numpy pandas scikit-learn 
 
+      - name: Install DVC
+        run: pip install dvc[s3]
+
+      - name: Configure DVC remote
+        run: |
+          dvc remote add -d s3remote s3://myremote-s3-bucket
+          # dvc remote modify s3remote endpointurl https://s3.amazonaws.com # Modify this if you have a custom S3 endpoint
+
+      - name: Set AWS Credentials
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+          aws configure set region ${{ secrets.AWS_REGION }}
+
+      - name: Pull DVC data
+        run: dvc pull 
+
       - name: Linting
         run: |
           pip install flake8
@@ -32,64 +52,64 @@ jobs:
         run: |
           python -m unittest discover
 
-      - name: Build Docker image
-        run: |
-          echo "Latest Docker file is running ..."
-          docker build -t wine-quality-detector:latest .
+      # - name: Build Docker image
+      #   run: |
+      #     echo "Latest Docker file is running ..."
+      #     docker build -t wine-quality-detector:latest .
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+      # - name: Login to Docker Hub
+      #   uses: docker/login-action@v2
+      #   with:
+      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
+      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-      - name: Push Docker image to Docker Hub
-        run: |
-          echo "pushing the Docker file to DockerHUB ..."
-          docker tag wine-quality-detector:latest ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
-          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
-      - name: Set up SSH key
-        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
-        with:
-          ORIGIN: ${{ secrets.EC2_HOST }} 
-          SSHKEY: ${{ secrets.EC2_SSH_KEY }}
-          NAME: production
-          PORT: 22
-          USER: ${{ secrets.EC2_USER }} 
-      - name: Deploy Docker Image
-        run: |
-          ssh production << 'EOF'
-            # Ensure Docker is installed
-            if ! command -v docker &> /dev/null
-            then
-                echo "Docker could not be found, installing..."
-                sudo yum update -y
-                sudo amazon-linux-extras install docker -y
-                sudo service docker start
-                sudo usermod -a -G docker ec2-user
-                sudo chkconfig docker on
-            fi
+      # - name: Push Docker image to Docker Hub
+      #   run: |
+      #     echo "pushing the Docker file to DockerHUB ..."
+      #     docker tag wine-quality-detector:latest ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
+      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
+      # - name: Set up SSH key
+      #   uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
+      #   with:
+      #     ORIGIN: ${{ secrets.EC2_HOST }} 
+      #     SSHKEY: ${{ secrets.EC2_SSH_KEY }}
+      #     NAME: production
+      #     PORT: 22
+      #     USER: ${{ secrets.EC2_USER }} 
+      # - name: Deploy Docker Image
+      #   run: |
+      #     ssh production << 'EOF'
+      #       # Ensure Docker is installed
+      #       if ! command -v docker &> /dev/null
+      #       then
+      #           echo "Docker could not be found, installing..."
+      #           sudo yum update -y
+      #           sudo amazon-linux-extras install docker -y
+      #           sudo service docker start
+      #           sudo usermod -a -G docker ec2-user
+      #           sudo chkconfig docker on
+      #       fi
 
-            # Ensure Docker service is running
-            sudo service docker start
+      #       # Ensure Docker service is running
+      #       sudo service docker start
 
-            # Ensure the current user is in the docker group
-            if ! groups $USER | grep &>/dev/null '\bdocker\b'; then
-                sudo usermod -aG docker $USER
-                newgrp docker
-            fi
+      #       # Ensure the current user is in the docker group
+      #       if ! groups $USER | grep &>/dev/null '\bdocker\b'; then
+      #           sudo usermod -aG docker $USER
+      #           newgrp docker
+      #       fi
 
-            # Update Docker credentials
-            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
+      #       # Update Docker credentials
+      #       echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
 
-            # Stop and remove any existing container
-            sudo docker stop my-container || true
-            sudo docker rm my-container || true
+      #       # Stop and remove any existing container
+      #       sudo docker stop my-container || true
+      #       sudo docker rm my-container || true
             
-            # Pull the latest Docker image from Docker Hub
-            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
+      #       # Pull the latest Docker image from Docker Hub
+      #       sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
             
-            # Run the Docker container
-            echo "Waiting for the Docker container to start..."
-            sudo docker run -d --name my-container -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
-          EOF
+      #       # Run the Docker container
+      #       echo "Waiting for the Docker container to start..."
+      #       sudo docker run -d --name my-container -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
+      #     EOF
