expermineting with ci-cd.yml v2

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -54,7 +54,39 @@ jobs:
           NAME: production
           PORT: 22
           USER: ${{ secrets.EC2_USER }} 
-      - run: ssh production "ls -la;id; echo hehe > h.txt "
+      # - run: ssh production "ls -la;id; echo hehe > h.txt "
+
+
+      - name: Deploy Docker Image
+        run: |
+          ssh production << 'EOF'
+            # Ensure Docker is installed
+            if ! command -v docker &> /dev/null
+            then
+                echo "Docker could not be found, installing..."
+                sudo yum update -y
+                sudo amazon-linux-extras install docker -y
+                sudo service docker start
+                sudo usermod -a -G docker ec2-user
+                sudo chkconfig docker on
+            fi
+
+            # Ensure Docker service is running
+            sudo service docker start
+
+            # Update Docker credentials
+            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
+
+            # Stop and remove any existing container
+            docker stop my-container || true
+            docker rm my-container || true
+            
+            # Pull the latest Docker image from Docker Hub
+            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
+            
+            # Run the Docker container
+            docker run -d --name my-container -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-detector:latest
+          EOF
       # - name: SSH into EC2 and deploy
       #   uses: appleboy/ssh-action@master
       #   with:
